ubuntu:
  build: .
  ports:
   - '8080:8080'
  environment:
    SERVER_LOG_MINIMAL: 1
    SERVER_APP_NAME: docker-test
    S6_KILL_FINISH_MAXTIME: 1
    S6_KILL_GRACETIME: 1
alpine:
  build: .
  dockerfile: Dockerfile-alpine
  ports:
   - '8081:8080'
  environment:
    SERVER_LOG_MINIMAL: 1
    SERVER_APP_NAME: docker-test
    S6_KILL_FINISH_MAXTIME: 1
    S6_KILL_GRACETIME: 1
